services:
  mock-simulator:
    extends:
      file: ./docker-compose.yml
      service: mock-simulator
    environment:
      MOCK_SCENARIO: widget_test

  carla-client:
    extends:
      file: ./docker-compose.yml
      service: carla-client
    profiles: ["disabled"]

  io-client:
    extends:
      file: ./docker-compose.yml
      service: io-client
    profiles: ["disabled"]

networks:
  scarline-net:
    driver: bridge
