import type { FastifyInstance, FastifyRequest } from "fastify";
import type { Pool } from "pg";
import { z } from "zod";
import {
  CarlaSessionConfigurationSchema,
  TriggerActionTypeSchema,
  TriggerExpressionSchema,
  LayoutTypeSchema,
  ParticipantLayoutBulkSaveSchema,
  WidgetWindowModeSchema,
} from "@scarline/contracts";

import { authenticate, requireAnyRole, requirePasswordReady } from "../auth/guards.js";
import type { AuthService } from "../auth/service.js";
import { ApiProblem } from "../errors.js";
import {
  WidgetCatalogueService,
  WidgetCatalogueValidationError,
} from "../widgets/catalogue.js";
import { AuthHeadersSchema, EmptyObjectSchema, UuidParamsSchema, success } from "./common.js";
import { ensureStudyAccess, requireEditableStudy, requireRemovableStudyConfiguration } from "./studies.js";
import type { RealtimeHub } from "../realtime/hub.js";
import { saveParticipantLayouts } from "../layouts/bulk-save.js";

const ConditionParamsSchema=z.object({studyId:z.string().uuid(),conditionId:z.string().uuid()}).strict();
const StudyOnlyParamsSchema=z.object({studyId:z.string().uuid()}).strict();
const ConditionEntityParamsSchema=z.object({studyId:z.string().uuid(),conditionId:z.string().uuid(),id:z.string().uuid()}).strict();
const DeviceSensorParamsSchema=z.object({deviceId:z.string().uuid(),id:z.string().uuid()}).strict();
const LayoutParamsSchema=z.object({studyId:z.string().uuid(),conditionId:z.string().uuid(),layoutId:z.string().uuid()}).strict();
const LayoutEntityParamsSchema=LayoutParamsSchema.extend({id:z.string().uuid()}).strict();
const JsonSchema=z.record(z.string(),z.unknown());
const SimulatorSchema=z.object({simulatorType:z.enum(["carla","mock"]),configuration:JsonSchema.default({})}).strict().superRefine((value,context)=>{
  if(value.simulatorType!=="carla")return;
  const parsed=CarlaSessionConfigurationSchema.safeParse(value.configuration);
  if(!parsed.success)for(const issue of parsed.error.issues)context.addIssue({code:"custom",path:["configuration",...issue.path],message:issue.message});
});
const DeviceSchema=z.object({name:z.string().min(1).max(200),type:z.string().min(1).max(50),sourceKey:z.string().max(200).nullable().default(null),configuration:JsonSchema.default({}),displayConfiguration:JsonSchema.default({}),metadata:JsonSchema.default({})}).strict();
const DevicePatchSchema=DeviceSchema.partial().extend({status:z.enum(["disconnected","connecting","connected","error","disabled"]).optional(),statusMessage:z.string().nullable().optional()}).strict();
const SensorSchema=z.object({key:z.string().min(1).max(100),name:z.string().min(1).max(200),modality:z.string().max(50).nullable().default(null),unit:z.string().max(50).nullable().default(null),metadata:JsonSchema.default({})}).strict();
const AttachDeviceSchema=z.object({deviceId:z.string().uuid(),enabled:z.boolean().default(true),configuration:JsonSchema.default({})}).strict();
const ConditionDevicePatchSchema=z.object({enabled:z.boolean().optional(),configuration:JsonSchema.optional()}).strict();
const SensorConfigurationSchema=z.object({sensorId:z.string().uuid(),enabled:z.boolean().default(true),configuration:JsonSchema.default({})}).strict();
const LayoutSchema=z.object({name:z.string().min(1).max(200),type:LayoutTypeSchema,targetDisplay:z.string().max(100).nullable().default(null),layoutConfig:JsonSchema.default({})}).strict();
const LayoutPatchSchema=LayoutSchema.partial().strict();
const WidgetInstanceSchema=z.object({widgetId:z.string().uuid(),windowMode:WidgetWindowModeSchema,targetDisplay:z.string().min(1).max(100),order:z.number().int().nonnegative().default(0),x:z.number().int(),y:z.number().int(),width:z.number().int().positive(),height:z.number().int().positive(),enabled:z.boolean().default(true),configuration:JsonSchema.default({}),bindingsConfig:JsonSchema.default({}),styleOverrides:JsonSchema.default({})}).strict();
const WidgetInstancePatchSchema=WidgetInstanceSchema.partial().strict();
const TriggerSchema=z.object({name:z.string().min(1).max(200),description:z.string().nullable().default(null),expression:TriggerExpressionSchema,actionType:TriggerActionTypeSchema,actionConfig:JsonSchema.default({}),enabled:z.boolean().default(true),priority:z.number().int().nonnegative().default(100),cooldownMs:z.number().int().nonnegative().default(0)}).strict();
const TriggerPatchSchema=TriggerSchema.partial().strict();

async function authorizeCondition(request:FastifyRequest,pool:Pool,studyId:string,conditionId:string,editable:boolean):Promise<void>{
  await ensureStudyAccess(request,pool,studyId); if(editable)await requireEditableStudy(pool,studyId);
  const found=await pool.query("SELECT 1 FROM conditions WHERE id=$1 AND study_id=$2",[conditionId,studyId]); if(found.rowCount!==1)throw new ApiProblem(404,"CONDITION_NOT_FOUND","Condition not found.");
}

export async function registerConfigurationRoutes(app:FastifyInstance,pool:Pool,auth:AuthService,widgets:WidgetCatalogueService,realtime:RealtimeHub):Promise<void>{
  const read=[authenticate(auth),requirePasswordReady]; const design=[...read,requireAnyRole("admin","researcher")]; const admin=[...read,requireAnyRole("admin")];

  app.get("/api/v1/studies/:studyId/conditions/:conditionId/simulator",{preHandler:read,schema:{params:ConditionParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema}},async request=>{const p=ConditionParamsSchema.parse(request.params);await authorizeCondition(request,pool,p.studyId,p.conditionId,false);const r=await pool.query(`SELECT id,"condition_id" AS "conditionId",simulator_type AS "simulatorType",configuration,created_at AS "createdAt",updated_at AS "updatedAt" FROM simulator_configurations WHERE condition_id=$1`,[p.conditionId]);return success(r.rows[0]??null);});
  app.put("/api/v1/studies/:studyId/conditions/:conditionId/simulator",{preHandler:design,schema:{params:ConditionParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:SimulatorSchema}},async request=>{const p=ConditionParamsSchema.parse(request.params),b=SimulatorSchema.parse(request.body);await authorizeCondition(request,pool,p.studyId,p.conditionId,true);const r=await pool.query(`INSERT INTO simulator_configurations(condition_id,simulator_type,configuration)VALUES($1,$2,$3::jsonb) ON CONFLICT(condition_id)DO UPDATE SET simulator_type=EXCLUDED.simulator_type,configuration=EXCLUDED.configuration RETURNING id,condition_id AS "conditionId",simulator_type AS "simulatorType",configuration,created_at AS "createdAt",updated_at AS "updatedAt"`,[p.conditionId,b.simulatorType,JSON.stringify(b.configuration)]);return success(r.rows[0]);});

  app.get("/api/v1/devices",{preHandler:read,schema:{params:EmptyObjectSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema}},async()=>{const r=await pool.query(`SELECT id,name,type,source_key AS "sourceKey",status,status_message AS "statusMessage",configuration,display_configuration AS "displayConfiguration",metadata,last_seen_at AS "lastSeenAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM devices ORDER BY name`);return success(r.rows);});
  app.post("/api/v1/devices",{preHandler:admin,schema:{params:EmptyObjectSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:DeviceSchema}},async(request,reply)=>{const b=DeviceSchema.parse(request.body);const r=await pool.query(`INSERT INTO devices(name,type,source_key,configuration,display_configuration,metadata)VALUES($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb)RETURNING *`,[b.name,b.type,b.sourceKey,JSON.stringify(b.configuration),JSON.stringify(b.displayConfiguration),JSON.stringify(b.metadata)]);return reply.status(201).send(success(r.rows[0]));});
  app.patch("/api/v1/devices/:id",{preHandler:admin,schema:{params:UuidParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:DevicePatchSchema}},async request=>{const{id}=UuidParamsSchema.parse(request.params),b=DevicePatchSchema.parse(request.body);const r=await pool.query(`UPDATE devices SET name=COALESCE($2,name),type=COALESCE($3,type),source_key=CASE WHEN $4 THEN $5 ELSE source_key END,status=COALESCE($6,status),status_message=CASE WHEN $7 THEN $8 ELSE status_message END,configuration=COALESCE($9::jsonb,configuration),display_configuration=COALESCE($10::jsonb,display_configuration),metadata=COALESCE($11::jsonb,metadata)WHERE id=$1 RETURNING *`,[id,b.name??null,b.type??null,"sourceKey" in b,b.sourceKey??null,b.status??null,"statusMessage" in b,b.statusMessage??null,b.configuration===undefined?null:JSON.stringify(b.configuration),b.displayConfiguration===undefined?null:JSON.stringify(b.displayConfiguration),b.metadata===undefined?null:JSON.stringify(b.metadata)]);if(!r.rows[0])throw new ApiProblem(404,"DEVICE_NOT_FOUND","Device not found.");return success(r.rows[0]);});
  app.delete("/api/v1/devices/:id",{preHandler:admin,schema:{params:UuidParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema}},async(request,reply)=>{const{id}=UuidParamsSchema.parse(request.params);const used=await pool.query("SELECT 1 FROM condition_devices WHERE device_id=$1 LIMIT 1",[id]);if(used.rowCount===1)await pool.query("UPDATE devices SET status='disabled',status_message='Disabled because historical or configured use exists' WHERE id=$1",[id]);else await pool.query("DELETE FROM devices WHERE id=$1",[id]);return reply.status(204).send();});

  app.get("/api/v1/devices/:id/sensors",{preHandler:read,schema:{params:UuidParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema}},async request=>{const{id}=UuidParamsSchema.parse(request.params);const r=await pool.query(`SELECT id,device_id AS "deviceId",key,name,modality,unit,metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM device_sensors WHERE device_id=$1 AND is_active ORDER BY key`,[id]);return success(r.rows);});
  app.post("/api/v1/devices/:id/sensors",{preHandler:admin,schema:{params:UuidParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:SensorSchema}},async(request,reply)=>{const{id}=UuidParamsSchema.parse(request.params),b=SensorSchema.parse(request.body);const r=await pool.query(`INSERT INTO device_sensors(device_id,key,name,modality,unit,metadata)VALUES($1,$2,$3,$4,$5,$6::jsonb)RETURNING *`,[id,b.key,b.name,b.modality,b.unit,JSON.stringify(b.metadata)]);return reply.status(201).send(success(r.rows[0]));});
  app.delete("/api/v1/devices/:deviceId/sensors/:id",{preHandler:admin,schema:{params:DeviceSensorParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema}},async(request,reply)=>{const p=DeviceSensorParamsSchema.parse(request.params);const used=await pool.query("SELECT 1 FROM condition_sensor_configurations WHERE sensor_id=$1 LIMIT 1",[p.id]);if(used.rowCount===1)throw new ApiProblem(409,"SENSOR_IN_USE","A configured sensor cannot be deleted; disable its configuration instead.");await pool.query("DELETE FROM device_sensors WHERE id=$1 AND device_id=$2",[p.id,p.deviceId]);return reply.status(204).send();});

  app.get("/api/v1/studies/:studyId/conditions/:conditionId/devices",{preHandler:read,schema:{params:ConditionParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema}},async request=>{const p=ConditionParamsSchema.parse(request.params);await authorizeCondition(request,pool,p.studyId,p.conditionId,false);const r=await pool.query(`SELECT cd.id,cd.condition_id AS "conditionId",cd.device_id AS "deviceId",d.name,d.type,cd.enabled,cd.configuration,cd.created_at AS "createdAt",cd.updated_at AS "updatedAt" FROM condition_devices cd JOIN devices d ON d.id=cd.device_id WHERE cd.condition_id=$1 ORDER BY d.name`,[p.conditionId]);return success(r.rows);});
  app.post("/api/v1/studies/:studyId/conditions/:conditionId/devices",{preHandler:design,schema:{params:ConditionParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:AttachDeviceSchema}},async(request,reply)=>{const p=ConditionParamsSchema.parse(request.params),b=AttachDeviceSchema.parse(request.body);await authorizeCondition(request,pool,p.studyId,p.conditionId,true);const r=await pool.query(`INSERT INTO condition_devices(condition_id,device_id,enabled,configuration)VALUES($1,$2,$3,$4::jsonb)ON CONFLICT(condition_id,device_id)DO UPDATE SET enabled=EXCLUDED.enabled,configuration=EXCLUDED.configuration RETURNING *`,[p.conditionId,b.deviceId,b.enabled,JSON.stringify(b.configuration)]);return reply.status(201).send(success(r.rows[0]));});
  app.patch("/api/v1/studies/:studyId/conditions/:conditionId/devices/:id",{preHandler:design,schema:{params:ConditionEntityParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:ConditionDevicePatchSchema}},async request=>{const p=ConditionEntityParamsSchema.parse(request.params),b=ConditionDevicePatchSchema.parse(request.body);await authorizeCondition(request,pool,p.studyId,p.conditionId,true);const r=await pool.query(`UPDATE condition_devices SET enabled=COALESCE($3,enabled),configuration=COALESCE($4::jsonb,configuration)WHERE id=$1 AND condition_id=$2 RETURNING *`,[p.id,p.conditionId,b.enabled??null,b.configuration===undefined?null:JSON.stringify(b.configuration)]);if(!r.rows[0])throw new ApiProblem(404,"CONDITION_DEVICE_NOT_FOUND","Condition device not found.");return success(r.rows[0]);});
  app.delete("/api/v1/studies/:studyId/conditions/:conditionId/devices/:id",{preHandler:design,schema:{params:ConditionEntityParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema}},async(request,reply)=>{const p=ConditionEntityParamsSchema.parse(request.params);await authorizeCondition(request,pool,p.studyId,p.conditionId,false);const study=await requireRemovableStudyConfiguration(pool,p.studyId);const historical=await pool.query("SELECT 1 FROM session_conditions WHERE condition_id=$1 LIMIT 1",[p.conditionId]);if(historical.rowCount===1||study.status==="completed")await pool.query("UPDATE condition_devices SET enabled=FALSE WHERE id=$1 AND condition_id=$2",[p.id,p.conditionId]);else await pool.query("DELETE FROM condition_devices WHERE id=$1 AND condition_id=$2",[p.id,p.conditionId]);return reply.status(204).send();});
  app.put("/api/v1/studies/:studyId/conditions/:conditionId/devices/:id/sensors",{preHandler:design,schema:{params:ConditionEntityParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:SensorConfigurationSchema}},async request=>{const p=ConditionEntityParamsSchema.parse(request.params),b=SensorConfigurationSchema.parse(request.body);await authorizeCondition(request,pool,p.studyId,p.conditionId,true);const device=await pool.query<{device_id:string}>("SELECT device_id FROM condition_devices WHERE id=$1 AND condition_id=$2",[p.id,p.conditionId]);if(!device.rows[0])throw new ApiProblem(404,"CONDITION_DEVICE_NOT_FOUND","Condition device not found.");const r=await pool.query(`INSERT INTO condition_sensor_configurations(condition_device_id,device_id,sensor_id,enabled,configuration)VALUES($1,$2,$3,$4,$5::jsonb)ON CONFLICT(condition_device_id,sensor_id)DO UPDATE SET enabled=EXCLUDED.enabled,configuration=EXCLUDED.configuration RETURNING *`,[p.id,device.rows[0].device_id,b.sensorId,b.enabled,JSON.stringify(b.configuration)]);return success(r.rows[0]);});

  registerLayoutRoutes(app,pool,auth,realtime);
  registerTriggerRoutes(app,pool,auth);
  registerWidgetCatalogue(app,auth,widgets);
}

function registerLayoutRoutes(app:FastifyInstance,pool:Pool,auth:AuthService,realtime:RealtimeHub):void{
  const read=[authenticate(auth),requirePasswordReady],design=[...read,requireAnyRole("admin","researcher")];
  app.put("/api/v1/studies/:studyId/layouts/participant",{preHandler:design,schema:{params:StudyOnlyParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:ParticipantLayoutBulkSaveSchema}},async request=>{const{studyId}=StudyOnlyParamsSchema.parse(request.params),body=ParticipantLayoutBulkSaveSchema.parse(request.body);await ensureStudyAccess(request,pool,studyId);await requireEditableStudy(pool,studyId);const status=realtime.overlayStatus as {connected?:boolean;displays?:Array<{id?:unknown;index?:unknown}>};const validDisplays=status.connected===true&&Array.isArray(status.displays)&&status.displays.length>0?new Set(status.displays.flatMap((display)=>[String(display.id??""),String(display.index??"")]).filter(Boolean)):null;return success(await saveParticipantLayouts(pool,studyId,body,validDisplays));});
  app.get("/api/v1/studies/:studyId/conditions/:conditionId/layouts",{preHandler:read,schema:{params:ConditionParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema}},async request=>{const p=ConditionParamsSchema.parse(request.params);await authorizeCondition(request,pool,p.studyId,p.conditionId,false);const r=await pool.query(`SELECT l.id,l.condition_id AS "conditionId",l.name,l.type,l.target_display AS "targetDisplay",l.layout_config AS "layoutConfig",l.revision,l.created_at AS "createdAt",l.updated_at AS "updatedAt",COALESCE(json_agg(json_build_object('id',wi.id,'widgetId',wi.widget_id,'windowMode',wi.window_mode,'inputMode',wi.input_mode,'targetDisplay',wi.target_display,'order',wi."order",'x',wi.x,'y',wi.y,'width',wi.width,'height',wi.height,'enabled',wi.enabled,'configuration',wi.configuration,'bindingsConfig',wi.bindings_config,'styleOverrides',wi.style_overrides))FILTER(WHERE wi.id IS NOT NULL),'[]')AS widgets FROM layouts l LEFT JOIN widget_instances wi ON wi.layout_id=l.id WHERE l.condition_id=$1 GROUP BY l.id ORDER BY l.name`,[p.conditionId]);return success(r.rows);});
  app.post("/api/v1/studies/:studyId/conditions/:conditionId/layouts",{preHandler:design,schema:{params:ConditionParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:LayoutSchema}},async(request,reply)=>{const p=ConditionParamsSchema.parse(request.params),b=LayoutSchema.parse(request.body);await authorizeCondition(request,pool,p.studyId,p.conditionId,true);const r=await pool.query(`INSERT INTO layouts(condition_id,name,type,target_display,layout_config)VALUES($1,$2,$3,$4,$5::jsonb)RETURNING *`,[p.conditionId,b.name,b.type,b.targetDisplay,JSON.stringify(b.layoutConfig)]);return reply.status(201).send(success(r.rows[0]));});
  app.patch("/api/v1/studies/:studyId/conditions/:conditionId/layouts/:layoutId",{preHandler:design,schema:{params:LayoutParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:LayoutPatchSchema}},async request=>{const p=LayoutParamsSchema.parse(request.params),b=LayoutPatchSchema.parse(request.body);await authorizeCondition(request,pool,p.studyId,p.conditionId,true);const r=await pool.query(`UPDATE layouts SET name=COALESCE($3,name),type=COALESCE($4,type),target_display=CASE WHEN $5 THEN $6 ELSE target_display END,layout_config=COALESCE($7::jsonb,layout_config)WHERE id=$1 AND condition_id=$2 RETURNING *`,[p.layoutId,p.conditionId,b.name??null,b.type??null,"targetDisplay" in b,b.targetDisplay??null,b.layoutConfig===undefined?null:JSON.stringify(b.layoutConfig)]);if(!r.rows[0])throw new ApiProblem(404,"LAYOUT_NOT_FOUND","Layout not found.");return success(r.rows[0]);});
  app.delete("/api/v1/studies/:studyId/conditions/:conditionId/layouts/:layoutId",{preHandler:design,schema:{params:LayoutParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema}},async(request,reply)=>{const p=LayoutParamsSchema.parse(request.params);await authorizeCondition(request,pool,p.studyId,p.conditionId,true);await pool.query("DELETE FROM layouts WHERE id=$1 AND condition_id=$2",[p.layoutId,p.conditionId]);return reply.status(204).send();});
  app.post("/api/v1/studies/:studyId/conditions/:conditionId/layouts/:layoutId/widgets",{preHandler:design,schema:{params:LayoutParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:WidgetInstanceSchema}},async(request,reply)=>{const p=LayoutParamsSchema.parse(request.params),b=WidgetInstanceSchema.parse(request.body);await authorizeCondition(request,pool,p.studyId,p.conditionId,true);const r=await pool.query(`INSERT INTO widget_instances(layout_id,widget_id,window_mode,target_display,"order",x,y,width,height,enabled,configuration,bindings_config,style_overrides)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12::jsonb,$13::jsonb)RETURNING *`,[p.layoutId,b.widgetId,b.windowMode,b.targetDisplay,b.order,b.x,b.y,b.width,b.height,b.enabled,JSON.stringify(b.configuration),JSON.stringify(b.bindingsConfig),JSON.stringify(b.styleOverrides)]);return reply.status(201).send(success(r.rows[0]));});
  app.patch("/api/v1/studies/:studyId/conditions/:conditionId/layouts/:layoutId/widgets/:id",{preHandler:design,schema:{params:LayoutEntityParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:WidgetInstancePatchSchema}},async request=>{const p=LayoutEntityParamsSchema.parse(request.params),b=WidgetInstancePatchSchema.parse(request.body);await authorizeCondition(request,pool,p.studyId,p.conditionId,true);const r=await pool.query(`UPDATE widget_instances SET widget_id=COALESCE($3,widget_id),window_mode=COALESCE($4,window_mode),target_display=COALESCE($5,target_display),"order"=COALESCE($6,"order"),x=COALESCE($7,x),y=COALESCE($8,y),width=COALESCE($9,width),height=COALESCE($10,height),enabled=COALESCE($11,enabled),configuration=COALESCE($12::jsonb,configuration),bindings_config=COALESCE($13::jsonb,bindings_config),style_overrides=COALESCE($14::jsonb,style_overrides)WHERE id=$1 AND layout_id=$2 RETURNING *`,[p.id,p.layoutId,b.widgetId??null,b.windowMode??null,b.targetDisplay??null,b.order??null,b.x??null,b.y??null,b.width??null,b.height??null,b.enabled??null,b.configuration===undefined?null:JSON.stringify(b.configuration),b.bindingsConfig===undefined?null:JSON.stringify(b.bindingsConfig),b.styleOverrides===undefined?null:JSON.stringify(b.styleOverrides)]);if(!r.rows[0])throw new ApiProblem(404,"WIDGET_INSTANCE_NOT_FOUND","Widget instance not found.");return success(r.rows[0]);});
  app.delete("/api/v1/studies/:studyId/conditions/:conditionId/layouts/:layoutId/widgets/:id",{preHandler:design,schema:{params:LayoutEntityParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema}},async(request,reply)=>{const p=LayoutEntityParamsSchema.parse(request.params);await authorizeCondition(request,pool,p.studyId,p.conditionId,true);await pool.query("DELETE FROM widget_instances WHERE id=$1 AND layout_id=$2",[p.id,p.layoutId]);return reply.status(204).send();});
}

function registerTriggerRoutes(app:FastifyInstance,pool:Pool,auth:AuthService):void{
  const read=[authenticate(auth),requirePasswordReady],design=[...read,requireAnyRole("admin","researcher")];
  app.get("/api/v1/studies/:studyId/conditions/:conditionId/triggers",{preHandler:read,schema:{params:ConditionParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema}},async request=>{const p=ConditionParamsSchema.parse(request.params);await authorizeCondition(request,pool,p.studyId,p.conditionId,false);const r=await pool.query(`SELECT id,condition_id AS "conditionId",name,description,expression,action_type AS "actionType",action_config AS "actionConfig",enabled,priority,cooldown_ms AS "cooldownMs",created_at AS "createdAt",updated_at AS "updatedAt" FROM trigger_rules WHERE condition_id=$1 ORDER BY priority,name`,[p.conditionId]);return success(r.rows);});
  app.post("/api/v1/studies/:studyId/conditions/:conditionId/triggers",{preHandler:design,schema:{params:ConditionParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:TriggerSchema}},async(request,reply)=>{const p=ConditionParamsSchema.parse(request.params),b=TriggerSchema.parse(request.body);await authorizeCondition(request,pool,p.studyId,p.conditionId,true);const r=await pool.query(`INSERT INTO trigger_rules(condition_id,name,description,expression,action_type,action_config,enabled,priority,cooldown_ms)VALUES($1,$2,$3,$4::jsonb,$5,$6::jsonb,$7,$8,$9)RETURNING *`,[p.conditionId,b.name,b.description,JSON.stringify(b.expression),b.actionType,JSON.stringify(b.actionConfig),b.enabled,b.priority,b.cooldownMs]);return reply.status(201).send(success(r.rows[0]));});
  app.patch("/api/v1/studies/:studyId/conditions/:conditionId/triggers/:id",{preHandler:design,schema:{params:ConditionEntityParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:TriggerPatchSchema}},async request=>{const p=ConditionEntityParamsSchema.parse(request.params),b=TriggerPatchSchema.parse(request.body);await authorizeCondition(request,pool,p.studyId,p.conditionId,true);const r=await pool.query(`UPDATE trigger_rules SET name=COALESCE($3,name),description=CASE WHEN $4 THEN $5 ELSE description END,expression=COALESCE($6::jsonb,expression),action_type=COALESCE($7,action_type),action_config=COALESCE($8::jsonb,action_config),enabled=COALESCE($9,enabled),priority=COALESCE($10,priority),cooldown_ms=COALESCE($11,cooldown_ms)WHERE id=$1 AND condition_id=$2 RETURNING *`,[p.id,p.conditionId,b.name??null,"description" in b,b.description??null,b.expression===undefined?null:JSON.stringify(b.expression),b.actionType??null,b.actionConfig===undefined?null:JSON.stringify(b.actionConfig),b.enabled??null,b.priority??null,b.cooldownMs??null]);if(!r.rows[0])throw new ApiProblem(404,"TRIGGER_NOT_FOUND","Trigger not found.");return success(r.rows[0]);});
  app.delete("/api/v1/studies/:studyId/conditions/:conditionId/triggers/:id",{preHandler:design,schema:{params:ConditionEntityParamsSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema}},async(request,reply)=>{const p=ConditionEntityParamsSchema.parse(request.params);await authorizeCondition(request,pool,p.studyId,p.conditionId,true);await pool.query("DELETE FROM trigger_rules WHERE id=$1 AND condition_id=$2",[p.id,p.conditionId]);return reply.status(204).send();});
}

function registerWidgetCatalogue(app:FastifyInstance,auth:AuthService,widgets:WidgetCatalogueService):void{
  const read=[authenticate(auth),requirePasswordReady];
  const refresh=[...read,requireAnyRole("admin","researcher")];
  app.get("/api/v1/widgets/catalogue",{preHandler:read,schema:{params:EmptyObjectSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema}},async()=>success(await widgets.list()));
  app.post("/api/v1/widgets/refresh",{preHandler:refresh,schema:{params:EmptyObjectSchema,querystring:EmptyObjectSchema,headers:AuthHeadersSchema,body:EmptyObjectSchema}},async request=>{
    try{
      const result=await widgets.refresh(request.principal!.id);
      return success(result);
    }catch(error){
      if(error instanceof WidgetCatalogueValidationError)throw new ApiProblem(409,"WIDGET_CATALOGUE_INVALID",error.message,{issues:error.issues});
      throw error;
    }
  });
}
